const data = {
    products :[
        {
            _id :'1',
            name : 'Nike Slim Shirt',
            category : 'Shirts',
            image : '/images/p1.jpg',
            price :120,
            countInStock : 10,
            brand : 'Nike',
            rating : 4.5,
            numReviews : 10,
            description : 'high quality product',
        },
        {
            _id :'2',
            name : 'Adidas Slim Shirt',
            category : 'Shirts',
            image : '/images/p2.jpg',
            price :100,
            countInStock : 16,
            brand : 'Adidas',
            rating : 4.0,
            numReviews : 10,
            description : 'high quality product',
        },
        {
            _id :'3',
            name : 'Ralph Lauren Slim Shirt',
            category : 'Shirts',
            image : '/images/p3.jpg',
            price :150,
            countInStock : 6,
            brand : 'Ralph Lauren',
            rating : 3.8,
            numReviews : 7,
            description : 'high quality product',
        },
        {
            _id :'4',
            name : 'Nike Pants',
            category : 'Pants',
            image : '/images/p4.jpg',
            price :80,
            countInStock : 0,
            brand : 'Nike',
            rating : 4.5,
            numReviews : 5,
            description : 'high quality product',
        },
        {
            _id :'5',
            name : 'Adidas Pants',
            category : 'Pants',
            image : '/images/p5.jpg',
            price :100,
            countInStock : 3,
            brand : 'Adidas',
            rating : 4.6,
            numReviews : 10,
            description : 'high quality product',
        },
        {
            _id :'6',
            name : 'Ralph Lauren Pants',
            category : 'Pants',
            image : '/images/p6.jpg',
            price :150,
            countInStock : 7,
            brand : 'Ralph Lauren',
            rating : 4.0,
            numReviews : 16,
            description : 'high quality product',
        },
    ]
}

export default data;